/**
 * Redux Action Types
 * Defines all action type constants for the application
 */

// Auth actions
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE'

// Snippet actions
export const SNIPPET_FETCH_REQUEST = 'SNIPPET_FETCH_REQUEST'
export const SNIPPET_FETCH_SUCCESS = 'SNIPPET_FETCH_SUCCESS'
export const SNIPPET_FETCH_FAILURE = 'SNIPPET_FETCH_FAILURE'
export const SNIPPET_CREATE_REQUEST = 'SNIPPET_CREATE_REQUEST'
export const SNIPPET_CREATE_SUCCESS = 'SNIPPET_CREATE_SUCCESS'
export const SNIPPET_CREATE_FAILURE = 'SNIPPET_CREATE_FAILURE'
export const SNIPPET_UPDATE_REQUEST = 'SNIPPET_UPDATE_REQUEST'
export const SNIPPET_UPDATE_SUCCESS = 'SNIPPET_UPDATE_SUCCESS'
export const SNIPPET_UPDATE_FAILURE = 'SNIPPET_UPDATE_FAILURE'
export const SNIPPET_DELETE_REQUEST = 'SNIPPET_DELETE_REQUEST'
export const SNIPPET_DELETE_SUCCESS = 'SNIPPET_DELETE_SUCCESS'
export const SNIPPET_DELETE_FAILURE = 'SNIPPET_DELETE_FAILURE'

// Comment actions
export const COMMENT_FETCH_REQUEST = 'COMMENT_FETCH_REQUEST'
export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS'
export const COMMENT_FETCH_FAILURE = 'COMMENT_FETCH_FAILURE'
export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE'
export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE'

// UI actions
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
